# Generated by Django 5.0.7 on 2024-07-22 12:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartPars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageUrl', models.URLField(null=True)),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Город')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название аппартаментов')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание апартаментов')),
                ('price', models.CharField(max_length=100, verbose_name='Цена проживания за сутки')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkInDate', models.DateField(default=datetime.date.today)),
                ('checkOutDate', models.DateField(default=datetime.date.today)),
                ('contactPerson', models.CharField(blank=True, max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApart.apartpars')),
            ],
        ),
    ]
