# Generated by Django 5.0.7 on 2024-07-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartpars',
            name='priceNumber',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена проживания за сутки (число)'),
        ),
        migrations.AlterField(
            model_name='apartpars',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Цена проживания за сутки (текст)'),
        ),
    ]
